const WORKER_URL = window.WORKER_URL || window.location.origin;
const INACTIVITY_TIMEOUT_MS = 45000;

const translations = {
  en: { appTitle:"AI Conversation App", appSubtitle:"Choose a topic and let two AI agents discuss it in real time.", languageLabel:"Language", darkMode:"Dark mode", lightMode:"Light mode", controlsHeading:"Conversation controls", topicLabel:"Topic", roundsLabel:"Number of rounds", temperatureLabel:"Temperature", reasoningLabel:"Thinking / reasoning mode", reasoningHelp:"Applied only to models that support reasoning or thinking controls.", agentAModelLabel:"Agent A model", agentBModelLabel:"Agent B model", agentAModelHelp:"Select an approved Cloudflare Workers AI chat model for Agent A.", agentBModelHelp:"Select an approved Cloudflare Workers AI chat model for Agent B.", agentAPromptLabel:"Agent A system prompt", agentBPromptLabel:"Agent B system prompt", startButton:"Start conversation", clearButton:"Clear conversation", transcriptHeading:"Transcript", loadingModels:"Loading available models...", ready:"Ready", modelsError:"The available Cloudflare models could not be loaded. Check the Worker URL and deployment.", completed:"Conversation completed", approvedError:"Choose approved models for both agents before starting.", starting:"Starting conversation...", startError:"The conversation could not be started.", inactivityError:"The conversation stopped because no stream activity was received.", chars:"characters", reasoningTokens:"reasoning tokens" },
  ja: { appTitle:"AI会話アプリ", appSubtitle:"トピックを入力して、2つのAIエージェントの議論をリアルタイムで表示します。", languageLabel:"言語", darkMode:"ダークモード", lightMode:"ライトモード", controlsHeading:"会話設定", topicLabel:"トピック", roundsLabel:"ラウンド数", temperatureLabel:"温度", reasoningLabel:"思考／推論モード", reasoningHelp:"推論や思考設定に対応するモデルにのみ適用されます。", agentAModelLabel:"エージェントAのモデル", agentBModelLabel:"エージェントBのモデル", agentAModelHelp:"エージェントAに使う承認済みCloudflare Workers AIチャットモデルを選択します。", agentBModelHelp:"エージェントBに使う承認済みCloudflare Workers AIチャットモデルを選択します。", agentAPromptLabel:"エージェントAのシステムプロンプト", agentBPromptLabel:"エージェントBのシステムプロンプト", startButton:"会話を開始", clearButton:"会話をクリア", transcriptHeading:"会話ログ", loadingModels:"利用可能なモデルを読み込み中...", ready:"準備完了", modelsError:"利用可能なCloudflareモデルを読み込めませんでした。Worker URLとデプロイを確認してください。", completed:"会話が完了しました", approvedError:"開始前に両方のエージェントで承認済みモデルを選択してください。", starting:"会話を開始しています...", startError:"会話を開始できませんでした。", inactivityError:"ストリームの応答が一定時間なかったため、会話を停止しました。", chars:"文字", reasoningTokens:"推論トークン" }
};
let language = localStorage.getItem("language") || (navigator.language?.startsWith("ja") ? "ja" : "en");
let theme = localStorage.getItem("theme") || "light";

const form = document.querySelector("#debate-form");
const topicInput = document.querySelector("#topic");
const roundsInput = document.querySelector("#rounds");
const temperatureInput = document.querySelector("#temperature");
const reasoningModeSelect = document.querySelector("#reasoning-mode");
const agentAPromptInput = document.querySelector("#agent-a-prompt");
const agentBPromptInput = document.querySelector("#agent-b-prompt");
const agentAModelSelect = document.querySelector("#agent-a-model");
const agentBModelSelect = document.querySelector("#agent-b-model");
const languageSelect = document.querySelector("#language-select");
const themeToggle = document.querySelector("#theme-toggle");
const startButton = document.querySelector("#start-button");
const clearButton = document.querySelector("#clear-button");
const statusEl = document.querySelector("#status");
const errorEl = document.querySelector("#error");
const transcriptEl = document.querySelector("#transcript");

let approvedModelIds = new Set();
let modelNames = new Map();
let modelCapabilities = new Map();
let running = false;
let activeMessages = new Map();

function t(key) { return translations[language][key] || translations.en[key] || key; }
function applyLanguage() { document.documentElement.lang = language; languageSelect.value = language; document.querySelectorAll("[data-i18n]").forEach((el) => { el.textContent = t(el.dataset.i18n); }); themeToggle.textContent = theme === "dark" ? t("lightMode") : t("darkMode"); if (!running && approvedModelIds.size) setStatus(t("ready")); }
function applyTheme() { document.documentElement.dataset.theme = theme; themeToggle.textContent = theme === "dark" ? t("lightMode") : t("darkMode"); }
function setStatus(message) { statusEl.textContent = message; }
function setError(message = "") { errorEl.textContent = message; }
function setRunning(nextRunning) { running = nextRunning; const disabled = nextRunning || approvedModelIds.size === 0; startButton.disabled = disabled; agentAModelSelect.disabled = disabled; agentBModelSelect.disabled = disabled; roundsInput.disabled = nextRunning; temperatureInput.disabled = nextRunning; reasoningModeSelect.disabled = nextRunning; agentAPromptInput.disabled = nextRunning; agentBPromptInput.disabled = nextRunning; }
function shouldAutoScroll() { return transcriptEl.scrollHeight - transcriptEl.scrollTop - transcriptEl.clientHeight < 80; }
function scrollIfAppropriate(wasNearBottom) { if (wasNearBottom) transcriptEl.scrollTop = transcriptEl.scrollHeight; }
function appendOption(select, model) { const option = document.createElement("option"); option.value = model.id; option.textContent = model.supportsReasoning ? `${model.name} · reasoning` : model.name; select.append(option); }
async function loadModels() { setStatus(t("loadingModels")); setRunning(false); startButton.disabled = true; try { const response = await fetch(`${WORKER_URL}/models`, { method: "GET" }); if (!response.ok) throw new Error("MODELS_REQUEST_FAILED"); const data = await response.json(); if (!Array.isArray(data.models) || data.models.length === 0) throw new Error("MODELS_EMPTY"); agentAModelSelect.textContent = ""; agentBModelSelect.textContent = ""; approvedModelIds = new Set(); modelNames = new Map(); modelCapabilities = new Map(); for (const model of data.models) { if (!model || typeof model.id !== "string" || typeof model.name !== "string") continue; approvedModelIds.add(model.id); modelNames.set(model.id, model.name); modelCapabilities.set(model.id, model); appendOption(agentAModelSelect, model); appendOption(agentBModelSelect, model); } if (approvedModelIds.size === 0) throw new Error("NO_VALID_MODELS"); if (approvedModelIds.has(data.defaults?.agentA)) agentAModelSelect.value = data.defaults.agentA; if (approvedModelIds.has(data.defaults?.agentB)) agentBModelSelect.value = data.defaults.agentB; roundsInput.value = data.settings?.defaultRounds || 3; temperatureInput.value = data.settings?.defaultTemperature ?? 0.7; agentAPromptInput.value = data.prompts?.agentA || ""; agentBPromptInput.value = data.prompts?.agentB || ""; setStatus(t("ready")); setRunning(false); } catch (_) { approvedModelIds = new Set(); setStatus(t("modelsError")); startButton.disabled = true; agentAModelSelect.disabled = true; agentBModelSelect.disabled = true; } }
function validateSelectedModels() { return approvedModelIds.has(agentAModelSelect.value) && approvedModelIds.has(agentBModelSelect.value); }
function updateReasoningAvailability() { const a = modelCapabilities.get(agentAModelSelect.value); const b = modelCapabilities.get(agentBModelSelect.value); reasoningModeSelect.disabled = running || !(a?.supportsReasoning || b?.supportsReasoning); }
function createMessageCard({ agent, round, model }) { const wasNearBottom = shouldAutoScroll(); const card = document.createElement("article"); card.className = `message-card agent-${agent.toLowerCase()}`; const meta = document.createElement("div"); meta.className = "message-meta"; const title = document.createElement("strong"); title.textContent = `Agent ${agent} · Round ${round}`; const modelLabel = document.createElement("span"); modelLabel.textContent = modelNames.get(model) || model; meta.append(title, modelLabel); const content = document.createElement("div"); content.className = "message-content"; const stats = document.createElement("div"); stats.className = "message-stats"; stats.textContent = `0 ${t("chars")}`; card.append(meta, content, stats); transcriptEl.append(card); activeMessages.set(`${agent}:${round}`, { card, content, stats, characterCount: 0, reasoningTokens: 0 }); scrollIfAppropriate(wasNearBottom); }
function updateStats(message) { const parts = [`${message.characterCount} ${t("chars")}`]; if (message.reasoningTokens) parts.push(`${message.reasoningTokens} ${t("reasoningTokens")}`); message.stats.textContent = parts.join(" · "); }
function appendToken({ agent, round, content }) { const message = activeMessages.get(`${agent}:${round}`); if (!message || typeof content !== "string") return; const wasNearBottom = shouldAutoScroll(); message.content.append(document.createTextNode(content)); message.characterCount += [...content].length; updateStats(message); scrollIfAppropriate(wasNearBottom); }
function completeMessage({ agent, round, characterCount, reasoningTokens }) { const message = activeMessages.get(`${agent}:${round}`); if (message) { message.card.classList.add("complete"); if (Number.isFinite(characterCount)) message.characterCount = characterCount; if (Number.isFinite(reasoningTokens)) message.reasoningTokens = reasoningTokens; updateStats(message); } }
function parseSseEvents(buffer, onEvent) { const normalized = buffer.replace(/\r\n/g, "\n"); const parts = normalized.split("\n\n"); const remainder = parts.pop() || ""; for (const part of parts) { let event = "message"; const data = []; for (const line of part.split("\n")) { if (line.startsWith("event:")) event = line.slice(6).trim(); if (line.startsWith("data:")) data.push(line.slice(5).trimStart()); } if (data.length) onEvent(event, JSON.parse(data.join("\n"))); } return remainder; }
function handleStreamEvent(event, data) { if (event === "status") setStatus(data.message || "Working..."); if (event === "message_start") createMessageCard(data); if (event === "token") appendToken(data); if (event === "message_end") completeMessage(data); if (event === "done") setStatus(data.message || t("completed")); if (event === "error") throw new Error(data.message || "The AI service could not complete the conversation."); }
async function startConversation(event) { event.preventDefault(); setError(); if (!validateSelectedModels()) { setError(t("approvedError")); return; } setRunning(true); setStatus(t("starting")); const controller = new AbortController(); let timeoutId; const resetTimeout = () => { clearTimeout(timeoutId); timeoutId = setTimeout(() => controller.abort(), INACTIVITY_TIMEOUT_MS); }; resetTimeout(); try { const response = await fetch(`${WORKER_URL}/debate`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ topic: topicInput.value.trim(), rounds: Number(roundsInput.value), agentAModel: agentAModelSelect.value, agentBModel: agentBModelSelect.value, agentASystemPrompt: agentAPromptInput.value, agentBSystemPrompt: agentBPromptInput.value, temperature: Number(temperatureInput.value), reasoningMode: reasoningModeSelect.value }), signal: controller.signal }); if (!response.ok || !response.body) throw new Error(t("startError")); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; while (true) { const { value, done } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); buffer = parseSseEvents(buffer, (name, data) => { resetTimeout(); handleStreamEvent(name, data); }); } buffer += decoder.decode(); parseSseEvents(`${buffer}\n\n`, (name, data) => { resetTimeout(); handleStreamEvent(name, data); }); } catch (error) { setError(error.name === "AbortError" ? t("inactivityError") : error.message || "The AI service could not complete the conversation."); } finally { clearTimeout(timeoutId); setRunning(false); updateReasoningAvailability(); } }

form.addEventListener("submit", startConversation);
clearButton.addEventListener("click", () => { transcriptEl.textContent = ""; activeMessages = new Map(); setError(); if (!running) setStatus(t("ready")); });
languageSelect.addEventListener("change", () => { language = languageSelect.value; localStorage.setItem("language", language); applyLanguage(); activeMessages.forEach(updateStats); });
themeToggle.addEventListener("click", () => { theme = theme === "dark" ? "light" : "dark"; localStorage.setItem("theme", theme); applyTheme(); });
agentAModelSelect.addEventListener("change", updateReasoningAvailability);
agentBModelSelect.addEventListener("change", updateReasoningAvailability);
applyTheme();
applyLanguage();
loadModels().then(updateReasoningAvailability);
