const MAX_TOPIC_LENGTH = 1000;
const MAX_SYSTEM_PROMPT_LENGTH = 3000;
const MAX_MODEL_MESSAGES = 12;
const MAX_TOKENS = 1000;
const DEFAULT_ROUNDS = 3;
const AI_ERROR_MESSAGE = "The AI service could not complete the conversation.";
const SUPPORTED_MODELS = [
  { id: "@cf/openai/gpt-oss-120b", name: "GPT-OSS 120B", supportsReasoning: true, reasoningModes: ["low", "medium", "high"], supportsReasoningBudget: true },
  { id: "@cf/openai/gpt-oss-20b", name: "GPT-OSS 20B", supportsReasoning: true, reasoningModes: ["low", "medium", "high"], supportsReasoningBudget: true },
  { id: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b", name: "DeepSeek R1 Distill Qwen 32B", supportsReasoning: true, reasoningModes: ["auto"], supportsReasoningBudget: false },
  { id: "@cf/qwen/qwq-32b", name: "QwQ 32B", supportsReasoning: true, reasoningModes: ["auto"], supportsReasoningBudget: false },
  { id: "@cf/qwen/qwen3-30b-a3b-fp8", name: "Qwen3 30B A3B FP8", supportsReasoning: true, reasoningModes: ["auto"], supportsReasoningBudget: false },
  { id: "@cf/zai-org/glm-5.2", name: "GLM 5.2", supportsReasoning: true, reasoningModes: ["auto"], supportsReasoningBudget: false },
  { id: "@cf/zai-org/glm-4.7-flash", name: "GLM 4.7 Flash", supportsReasoning: false, reasoningModes: [], supportsReasoningBudget: false },
  { id: "@cf/moonshotai/kimi-k2.6", name: "Kimi K2.6", supportsReasoning: false, reasoningModes: [], supportsReasoningBudget: false },
  { id: "@cf/moonshotai/kimi-k2.7-code", name: "Kimi K2.7 Code", supportsReasoning: false, reasoningModes: [], supportsReasoningBudget: false },
  { id: "@cf/nvidia/nemotron-3-120b-a12b", name: "Nemotron 3 120B A12B", supportsReasoning: false, reasoningModes: [], supportsReasoningBudget: false },
  { id: "@cf/google/gemma-4-26b-a4b-it", name: "Gemma 4 26B A4B Instruct", supportsReasoning: false, reasoningModes: [], supportsReasoningBudget: false },
  { id: "@cf/google/gemma-3-12b-it", name: "Gemma 3 12B Instruct", supportsReasoning: false, reasoningModes: [], supportsReasoningBudget: false },
  { id: "@cf/meta/llama-4-scout-17b-16e-instruct", name: "Llama 4 Scout 17B 16E Instruct", supportsReasoning: false, reasoningModes: [], supportsReasoningBudget: false },
  { id: "@cf/meta/llama-3.3-70b-instruct-fp8-fast", name: "Llama 3.3 70B Instruct Fast", supportsReasoning: false, reasoningModes: [], supportsReasoningBudget: false },
  { id: "@cf/meta/llama-3.2-11b-vision-instruct", name: "Llama 3.2 11B Vision Instruct", supportsReasoning: false, reasoningModes: [], supportsReasoningBudget: false },
  { id: "@cf/meta/llama-3.2-3b-instruct", name: "Llama 3.2 3B Instruct", supportsReasoning: false, reasoningModes: [], supportsReasoningBudget: false },
  { id: "@cf/meta/llama-3.2-1b-instruct", name: "Llama 3.2 1B Instruct", supportsReasoning: false, reasoningModes: [], supportsReasoningBudget: false },
  { id: "@cf/meta/llama-3.1-8b-instruct", name: "Llama 3.1 8B Instruct", supportsReasoning: false, reasoningModes: [], supportsReasoningBudget: false },
  { id: "@cf/mistralai/mistral-small-3.1-24b-instruct", name: "Mistral Small 3.1 24B Instruct", supportsReasoning: false, reasoningModes: [], supportsReasoningBudget: false },
  { id: "@cf/qwen/qwen2.5-coder-32b-instruct", name: "Qwen2.5 Coder 32B Instruct", supportsReasoning: false, reasoningModes: [], supportsReasoningBudget: false }
];
const DEFAULT_AGENT = { name: "Agent 1", role: "Helpful research assistant", objective: "Answer the user clearly, concisely, and accurately.", model: "@cf/openai/gpt-oss-120b", temperature: 0.7, reasoningMode: "auto", reasoningBudget: 512, maxResponseChars: 1800 };
const REASONING_MODES = ["auto", "off", "low", "medium", "high"];
const BASE_REQUIREMENTS = `Be concise, relevant, and fact-based. Require citations or evidence for verifiable factual claims when sources are available. Clearly label unsupported claims as assumptions, inferences, or uncertainties. Convert broad topics into clear research questions and subquestions. Maintain shared records of facts, sources, assumptions, hypotheses, disputes, and unknowns. Every turn must move the discussion closer to a conclusion and avoid repeatedly introducing unrelated arguments. Generate and compare competing hypotheses, seek supporting evidence and counterevidence, identify connections or analogies from other fields, track agreements, disagreements, unresolved questions, and provisional conclusions, and stop adding material when another turn would not meaningfully improve the result.`;
function getAllowedOrigin(request, env) { const requestOrigin = request.headers.get("Origin"); const configuredOrigin = env.ALLOWED_ORIGIN || "*"; if (!requestOrigin) return configuredOrigin === "*" ? "*" : configuredOrigin; if (configuredOrigin === "*") return requestOrigin; return requestOrigin === configuredOrigin ? requestOrigin : null; }
function corsHeaders(request, env, contentType = "application/json; charset=utf-8") { const origin = getAllowedOrigin(request, env); if (!origin) return null; return { "Access-Control-Allow-Origin": origin, "Access-Control-Allow-Methods": "GET, POST, OPTIONS", "Access-Control-Allow-Headers": "Content-Type", "Vary": "Origin", ...(contentType ? { "Content-Type": contentType } : {}) }; }
function jsonResponse(request, env, body, status = 200) { const headers = corsHeaders(request, env); if (!headers) return new Response(JSON.stringify({ error: "Origin not allowed" }), { status: 403, headers: { "Content-Type": "application/json; charset=utf-8", "Vary": "Origin" } }); return new Response(JSON.stringify(body), { status, headers }); }
function sseEncode(event, data) { return `event: ${event}\ndata: ${JSON.stringify(data)}\n\n`; }
async function writeEvent(writer, encoder, event, data) { await writer.write(encoder.encode(sseEncode(event, data))); }
function validateModel(id) { return typeof id === "string" ? SUPPORTED_MODELS.find((model) => model.id === id) : null; }
function clampNumber(value, fallback, min, max) { const n = Number(value); return Number.isFinite(n) ? Math.min(max, Math.max(min, n)) : fallback; }
function clean(value, fallback, max = MAX_SYSTEM_PROMPT_LENGTH) { return typeof value === "string" && value.trim() ? value.trim().slice(0, max) : fallback; }
function normalizeAgents(body) { const raw = Array.isArray(body.agents) && body.agents.length ? body.agents : [DEFAULT_AGENT]; return raw.slice(0, 8).map((agent, index) => { const modelInfo = validateModel(agent.model || DEFAULT_AGENT.model); if (!modelInfo) return null; const reasoningMode = REASONING_MODES.includes(agent.reasoningMode) ? agent.reasoningMode : "auto"; return { id: `agent-${index + 1}`, name: clean(agent.name, `Agent ${index + 1}`, 80), role: clean(agent.role, DEFAULT_AGENT.role), objective: clean(agent.objective, DEFAULT_AGENT.objective), modelInfo, temperature: clampNumber(agent.temperature, DEFAULT_AGENT.temperature, 0, 2), reasoningMode, reasoningBudget: Math.round(clampNumber(agent.reasoningBudget, DEFAULT_AGENT.reasoningBudget, 0, 8192)), maxResponseChars: Math.round(clampNumber(agent.maxResponseChars, DEFAULT_AGENT.maxResponseChars, 400, 6000)) }; }); }
function extractText(payload) { if (!payload || typeof payload !== "object") return ""; if (typeof payload.response === "string") return payload.response; if (typeof payload.result?.response === "string") return payload.result.response; if (typeof payload.output_text === "string") return payload.output_text; const delta = payload.choices?.[0]?.delta?.content ?? payload.choices?.[0]?.text ?? payload.delta?.content; return typeof delta === "string" ? delta : ""; }
function extractReasoningTokens(payload) { const details = payload?.usage?.output_tokens_details || payload?.usage?.completion_tokens_details || payload?.result?.usage?.output_tokens_details || payload?.result?.usage?.completion_tokens_details; return Number(details?.reasoning_tokens) || 0; }
async function readWorkersAIStream(aiResponse, onText) { const stream = aiResponse?.body ? aiResponse.body : aiResponse; if (!stream?.getReader) throw new Error("AI_STREAM_UNAVAILABLE"); const reader = stream.getReader(); const decoder = new TextDecoder(); let buffer = ""; let complete = ""; let reasoningTokens = 0; async function processEvent(raw) { const dataLines = raw.split(/\r?\n/).filter((line) => line.startsWith("data:")).map((line) => line.slice(5).trimStart()); if (!dataLines.length) return; const data = dataLines.join("\n").trim(); if (!data || data === "[DONE]") return; const payload = JSON.parse(data); reasoningTokens += extractReasoningTokens(payload); const text = extractText(payload); if (text) { complete += text; await onText(text); } } while (true) { const { value, done } = await reader.read(); buffer += decoder.decode(value || new Uint8Array(), { stream: !done }); const parts = buffer.split(/\r?\n\r?\n/); buffer = parts.pop() || ""; for (const part of parts) await processEvent(part); if (done) break; } if (buffer.trim()) await processEvent(buffer); return { content: complete.trim(), reasoningTokens }; }
function sharedRecord(transcript) { return transcript.slice(-MAX_MODEL_MESSAGES).map((item) => `${item.name} (${item.phase}, round ${item.round}): ${item.content}`).join("\n\n") || "No prior turns."; }
function messagesFor({ agent, topic, transcript, phase, final = false }) { const system = `${BASE_REQUIREMENTS}\nRole: ${agent.role}\nObjective: ${agent.objective}\nMaximum response length: ${agent.maxResponseChars} characters. If your draft would exceed that limit, summarize or shorten it before answering. Use Markdown headings/lists for readability. Put detailed reasoning, evidence, and sources under separate Markdown sections, and keep the final conclusion easy to find.\n${final ? "You are the final evaluator and synthesizer. Assess accuracy, depth, novelty, and practical usefulness. Produce a structured deliverable with these headings: Main conclusion, Supporting facts, Remaining uncertainties, Recommended actions or next steps. Keep the final conclusion visible, do not introduce major new claims unless essential and supported by evidence, and hide no important caveats." : "Follow the current phase and your role. If you are a critic/red-team agent, challenge conclusions and hidden assumptions."}`; return [{ role: "system", content: system }, { role: "user", content: `Topic: ${topic}\nPhase: ${phase}\nCurrent turn: ${agent.currentTurn || "unknown"}. Remaining turns: ${agent.remainingTurns ?? "unknown"}. When only a few turns remain, prioritize conclusion mode: resolve disagreements and summarize findings.\nShared record:\n${sharedRecord(transcript)}\nUse any user-provided documents, URLs, APIs, calculator/code results, or tool outputs included in the topic/context. If actual tool access is unavailable, state that limitation and label claims accordingly.` }]; }
function aiOptions(agent, messages) { const options = { messages, max_tokens: MAX_TOKENS, stream: true, temperature: agent.temperature }; if (agent.modelInfo.supportsReasoning && agent.reasoningMode !== "auto" && agent.reasoningMode !== "off") options.reasoning = { effort: agent.reasoningMode, max_tokens: agent.modelInfo.supportsReasoningBudget ? agent.reasoningBudget : undefined }; return options; }
async function streamTurn({ env, agent, topic, transcript, round, phase, writer, encoder, final = false, currentTurn = 1, totalTurns = 1 }) { const turnAgent = { ...agent, currentTurn, remainingTurns: Math.max(0, totalTurns - currentTurn) }; await writeEvent(writer, encoder, "status", { message: `${agent.name} is working on ${phase}...`, currentTurn, remainingTurns: Math.max(0, totalTurns - currentTurn) }); await writeEvent(writer, encoder, "message_start", { agent: agent.name, round, model: agent.modelInfo.id, phase, currentTurn, remainingTurns: Math.max(0, totalTurns - currentTurn) }); const result = await readWorkersAIStream(await env.AI.run(agent.modelInfo.id, aiOptions(agent, messagesFor({ agent: turnAgent, topic, transcript, phase, final }))), (text) => writeEvent(writer, encoder, "token", { agent: agent.name, round, content: text })); if (!result.content) throw new Error("AI_EMPTY_RESPONSE"); await writeEvent(writer, encoder, "message_end", { agent: agent.name, round, characterCount: result.content.length, reasoningTokens: result.reasoningTokens }); transcript.push({ name: agent.name, round, phase, content: result.content }); }
async function handleDebate(request, env) { let body; try { body = await request.json(); } catch { return jsonResponse(request, env, { error: "Invalid JSON" }, 400); } const topic = clean(body.topic, "", MAX_TOPIC_LENGTH); const rounds = Math.round(clampNumber(body.rounds, DEFAULT_ROUNDS, 1, 50)); const agents = normalizeAgents(body); if (!topic || agents.some((agent) => !agent)) return jsonResponse(request, env, { error: "Invalid request" }, 400); const headers = corsHeaders(request, env, "text/event-stream; charset=utf-8"); if (!headers) return jsonResponse(request, env, { error: "Origin not allowed" }, 403); headers["Cache-Control"] = "no-cache"; const { readable, writable } = new TransformStream(); const writer = writable.getWriter(); const encoder = new TextEncoder(); (async () => { const transcript = []; try { const phases = agents.length === 1 ? ["conversation"] : ["exploration", "evaluation", "revision"]; const totalTurns = rounds * agents.length + 1; let currentTurn = 0; for (let round = 1; round <= rounds; round += 1) { const remainingRounds = rounds - round; const phase = remainingRounds <= 1 ? "conclusion mode" : phases[Math.min(round - 1, phases.length - 1)]; for (const agent of agents) await streamTurn({ env, agent, topic, transcript, round, phase, writer, encoder, currentTurn: ++currentTurn, totalTurns }); if (round >= 2 && transcript.at(-1)?.content.toLowerCase().includes("sufficiently supported conclusion") ) break; } const evaluator = { ...agents[0], name: "Final evaluator", role: "Evaluator", objective: "Synthesize and grade the discussion." }; await streamTurn({ env, agent: evaluator, topic, transcript, round: rounds + 1, phase: "final synthesis", writer, encoder, final: true, currentTurn: ++currentTurn, totalTurns: currentTurn }); await writeEvent(writer, encoder, "done", { message: "Conversation completed" }); } catch (_) { await writeEvent(writer, encoder, "error", { message: AI_ERROR_MESSAGE }); } finally { await writer.close(); } })(); return new Response(readable, { headers }); }
export default { async fetch(request, env) { const url = new URL(request.url); if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: corsHeaders(request, env, null) || { "Vary": "Origin" } }); if (url.pathname === "/health") return request.method === "GET" ? jsonResponse(request, env, { ok: true }) : jsonResponse(request, env, { error: "Method not allowed" }, 405); if (url.pathname === "/models") return request.method === "GET" ? jsonResponse(request, env, { models: SUPPORTED_MODELS, defaults: { agents: [DEFAULT_AGENT] }, settings: { defaultRounds: DEFAULT_ROUNDS, reasoningModes: REASONING_MODES } }) : jsonResponse(request, env, { error: "Method not allowed" }, 405); if (url.pathname === "/debate") return request.method === "POST" ? handleDebate(request, env) : jsonResponse(request, env, { error: "Method not allowed" }, 405); return jsonResponse(request, env, { error: "Not found" }, 404); } };
export { SUPPORTED_MODELS, readWorkersAIStream, handleDebate };
