const MAX_TOPIC_LENGTH = 500;
const MAX_SYSTEM_PROMPT_LENGTH = 3000;
const MAX_MODEL_MESSAGES = 8;
const MAX_TOKENS = 1000;
const MIN_WORDS = 10;
const DEFAULT_ROUNDS = 3;
const AI_ERROR_MESSAGE = "The AI service could not complete the conversation.";

// Cloudflare's Workers AI catalog changes over time. Review this manually maintained
// allowlist occasionally against the official Workers AI model catalog. It intentionally
// lists current text/conversation Workers AI models, including GPT-OSS reasoning models.
const SUPPORTED_MODELS = [
  { id: "@cf/openai/gpt-oss-120b", name: "GPT-OSS 120B", supportsReasoning: true, reasoningModes: ["low", "medium", "high"] },
  { id: "@cf/openai/gpt-oss-20b", name: "GPT-OSS 20B", supportsReasoning: true, reasoningModes: ["low", "medium", "high"] },
  { id: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b", name: "DeepSeek R1 Distill Qwen 32B", supportsReasoning: true, reasoningModes: ["auto"] },
  { id: "@cf/qwen/qwq-32b", name: "QwQ 32B", supportsReasoning: true, reasoningModes: ["auto"] },
  { id: "@cf/qwen/qwen3-30b-a3b-fp8", name: "Qwen3 30B A3B FP8", supportsReasoning: true, reasoningModes: ["auto"] },
  { id: "@cf/zai-org/glm-5.2", name: "GLM 5.2", supportsReasoning: true, reasoningModes: ["auto"] },
  { id: "@cf/zai-org/glm-4.7-flash", name: "GLM 4.7 Flash", supportsReasoning: false, reasoningModes: [] },
  { id: "@cf/moonshotai/kimi-k2.6", name: "Kimi K2.6", supportsReasoning: false, reasoningModes: [] },
  { id: "@cf/moonshotai/kimi-k2.7-code", name: "Kimi K2.7 Code", supportsReasoning: false, reasoningModes: [] },
  { id: "@cf/nvidia/nemotron-3-120b-a12b", name: "Nemotron 3 120B A12B", supportsReasoning: false, reasoningModes: [] },
  { id: "@cf/google/gemma-4-26b-a4b-it", name: "Gemma 4 26B A4B Instruct", supportsReasoning: false, reasoningModes: [] },
  { id: "@cf/google/gemma-3-12b-it", name: "Gemma 3 12B Instruct", supportsReasoning: false, reasoningModes: [] },
  { id: "@cf/aisingapore/gemma-sea-lion-v4-27b-it", name: "Gemma SEA-LION v4 27B Instruct", supportsReasoning: false, reasoningModes: [] },
  { id: "@cf/ibm-granite/granite-4.0-h-micro", name: "Granite 4.0 H Micro", supportsReasoning: false, reasoningModes: [] },
  { id: "@cf/meta/llama-4-scout-17b-16e-instruct", name: "Llama 4 Scout 17B 16E Instruct", supportsReasoning: false, reasoningModes: [] },
  { id: "@cf/meta/llama-3.3-70b-instruct-fp8-fast", name: "Llama 3.3 70B Instruct Fast", supportsReasoning: false, reasoningModes: [] },
  { id: "@cf/meta/llama-3.2-11b-vision-instruct", name: "Llama 3.2 11B Vision Instruct", supportsReasoning: false, reasoningModes: [] },
  { id: "@cf/meta/llama-3.2-3b-instruct", name: "Llama 3.2 3B Instruct", supportsReasoning: false, reasoningModes: [] },
  { id: "@cf/meta/llama-3.2-1b-instruct", name: "Llama 3.2 1B Instruct", supportsReasoning: false, reasoningModes: [] },
  { id: "@cf/meta/llama-3.1-8b-instruct-fp8", name: "Llama 3.1 8B Instruct FP8", supportsReasoning: false, reasoningModes: [] },
  { id: "@cf/meta/llama-3.1-8b-instruct", name: "Llama 3.1 8B Instruct", supportsReasoning: false, reasoningModes: [] },
  { id: "@cf/mistralai/mistral-small-3.1-24b-instruct", name: "Mistral Small 3.1 24B Instruct", supportsReasoning: false, reasoningModes: [] },
  { id: "@cf/qwen/qwen2.5-coder-32b-instruct", name: "Qwen2.5 Coder 32B Instruct", supportsReasoning: false, reasoningModes: [] }
];
const DEFAULT_AGENT_A_MODEL = "@cf/openai/gpt-oss-120b";
const DEFAULT_AGENT_B_MODEL = "@cf/meta/llama-3.3-70b-instruct-fp8-fast";
const REASONING_MODES = ["auto", "off", "low", "medium", "high"];
const RESPONSE_LENGTH_INSTRUCTION = "Produce a response of approximately 20 to 1,000 tokens. Even when there is little to add, provide at least one substantive sentence rather than an empty or one-word response. Never exceed the configured maximum output length.";
const DEFAULT_AGENT_A_SYSTEM_PROMPT = `You are Agent A, a thoughtful advocate who opens with constructive arguments and responds directly to Agent B. ${RESPONSE_LENGTH_INSTRUCTION}`;
const DEFAULT_AGENT_B_SYSTEM_PROMPT = `You are Agent B, a thoughtful skeptic who challenges assumptions while staying respectful and specific. ${RESPONSE_LENGTH_INSTRUCTION}`;

function getAllowedOrigin(request, env) { const requestOrigin = request.headers.get("Origin"); const configuredOrigin = env.ALLOWED_ORIGIN || "*"; if (!requestOrigin) return configuredOrigin === "*" ? "*" : configuredOrigin; if (configuredOrigin === "*") return requestOrigin; return requestOrigin === configuredOrigin ? requestOrigin : null; }
function corsHeaders(request, env, contentType = "application/json; charset=utf-8") { const origin = getAllowedOrigin(request, env); if (!origin) return null; return { "Access-Control-Allow-Origin": origin, "Access-Control-Allow-Methods": "GET, POST, OPTIONS", "Access-Control-Allow-Headers": "Content-Type", "Vary": "Origin", ...(contentType ? { "Content-Type": contentType } : {}) }; }
function jsonResponse(request, env, body, status = 200) { const headers = corsHeaders(request, env); if (!headers) return new Response(JSON.stringify({ error: "Origin not allowed" }), { status: 403, headers: { "Content-Type": "application/json; charset=utf-8", "Vary": "Origin" } }); return new Response(JSON.stringify(body), { status, headers }); }
function sseEncode(event, data) { return `event: ${event}\ndata: ${JSON.stringify(data)}\n\n`; }
async function writeEvent(writer, encoder, event, data) { await writer.write(encoder.encode(sseEncode(event, data))); }
function validateModel(id) { return typeof id === "string" ? SUPPORTED_MODELS.find((model) => model.id === id) : null; }
function validatePrompt(value, fallback) { if (typeof value !== "string") return fallback; const trimmed = value.trim(); return trimmed ? trimmed.slice(0, MAX_SYSTEM_PROMPT_LENGTH) : fallback; }
function validateTemperature(value) { const number = Number(value); return Number.isFinite(number) ? Math.min(2, Math.max(0, number)) : 0.7; }
function validateReasoningMode(value) { return REASONING_MODES.includes(value) ? value : "auto"; }
function buildMessages(systemPrompt, topic, transcript, retryTooShort) { const recent = transcript.slice(-MAX_MODEL_MESSAGES).map((item) => ({ role: item.agent === "A" ? "assistant" : "user", content: `Agent ${item.agent}, round ${item.round}: ${item.content}` })); return [{ role: "system", content: systemPrompt }, { role: "user", content: `Debate topic: ${topic}` }, ...recent, { role: "user", content: retryTooShort ? "Your previous response was too short. Give one concise but substantive explanation." : "Continue the debate from your assigned role." }]; }
function extractText(payload) { if (!payload || typeof payload !== "object") return ""; if (typeof payload.response === "string") return payload.response; if (typeof payload.result?.response === "string") return payload.result.response; if (typeof payload.output_text === "string") return payload.output_text; const delta = payload.choices?.[0]?.delta?.content ?? payload.choices?.[0]?.text ?? payload.delta?.content; return typeof delta === "string" ? delta : ""; }
function extractReasoningTokens(payload) { const details = payload?.usage?.output_tokens_details || payload?.usage?.completion_tokens_details || payload?.result?.usage?.output_tokens_details || payload?.result?.usage?.completion_tokens_details; return Number(details?.reasoning_tokens) || 0; }
async function readWorkersAIStream(aiResponse, onText) { const stream = aiResponse?.body ? aiResponse.body : aiResponse; if (!stream?.getReader) throw new Error("AI_STREAM_UNAVAILABLE"); const reader = stream.getReader(); const decoder = new TextDecoder(); let buffer = ""; let complete = ""; let reasoningTokens = 0; async function processEvent(raw) { const dataLines = raw.split(/\r?\n/).filter((line) => line.startsWith("data:")).map((line) => line.slice(5).trimStart()); if (!dataLines.length) return; const data = dataLines.join("\n").trim(); if (!data || data === "[DONE]") return; const payload = JSON.parse(data); reasoningTokens += extractReasoningTokens(payload); const text = extractText(payload); if (text) { complete += text; await onText(text); } } while (true) { const { value, done } = await reader.read(); buffer += decoder.decode(value || new Uint8Array(), { stream: !done }); const parts = buffer.split(/\r?\n\r?\n/); buffer = parts.pop() || ""; for (const part of parts) await processEvent(part); if (done) break; } if (buffer.trim()) await processEvent(buffer); return { content: complete, reasoningTokens }; }
function isUsable(text) { return text.trim().split(/\s+/).filter(Boolean).length >= MIN_WORDS; }
function buildAiOptions({ modelInfo, messages, temperature, reasoningMode }) { const options = { messages, max_tokens: MAX_TOKENS, stream: true, temperature }; if (modelInfo.supportsReasoning && reasoningMode !== "auto" && reasoningMode !== "off") options.reasoning = { effort: reasoningMode }; return options; }
async function streamAgentResponse({ env, modelInfo, systemPrompt, topic, transcript, agent, round, writer, encoder, temperature, reasoningMode, retryTooShort = false }) { await writeEvent(writer, encoder, "status", { message: `Agent ${agent} is thinking...` }); await writeEvent(writer, encoder, "message_start", { agent, round, model: modelInfo.id }); const messages = buildMessages(systemPrompt, topic, transcript, retryTooShort); const aiResponse = await env.AI.run(modelInfo.id, buildAiOptions({ modelInfo, messages, temperature, reasoningMode })); const result = await readWorkersAIStream(aiResponse, (text) => writeEvent(writer, encoder, "token", { agent, round, content: text })); const trimmed = result.content.trim(); if (!trimmed) throw new Error("AI_EMPTY_RESPONSE"); if (!isUsable(trimmed) && !retryTooShort) { await writeEvent(writer, encoder, "message_end", { agent, round, characterCount: trimmed.length, reasoningTokens: result.reasoningTokens }); return streamAgentResponse({ env, modelInfo, systemPrompt, topic, transcript, agent, round, writer, encoder, temperature, reasoningMode, retryTooShort: true }); } if (!isUsable(trimmed)) throw new Error("AI_TOO_SHORT"); await writeEvent(writer, encoder, "message_end", { agent, round, characterCount: trimmed.length, reasoningTokens: result.reasoningTokens }); transcript.push({ agent, round, content: trimmed }); return trimmed; }
async function handleDebate(request, env) { let body; try { body = await request.json(); } catch { return jsonResponse(request, env, { error: "Invalid JSON" }, 400); } const topic = typeof body.topic === "string" ? body.topic.trim() : ""; const rounds = Number(body.rounds ?? DEFAULT_ROUNDS); const agentAModelInfo = validateModel(body.agentAModel); const agentBModelInfo = validateModel(body.agentBModel); const agentASystemPrompt = validatePrompt(body.agentASystemPrompt, DEFAULT_AGENT_A_SYSTEM_PROMPT); const agentBSystemPrompt = validatePrompt(body.agentBSystemPrompt, DEFAULT_AGENT_B_SYSTEM_PROMPT); const temperature = validateTemperature(body.temperature); const reasoningMode = validateReasoningMode(body.reasoningMode); if (!topic || topic.length > MAX_TOPIC_LENGTH || !Number.isInteger(rounds) || rounds < 1) return jsonResponse(request, env, { error: "Invalid topic or rounds" }, 400); if (!agentAModelInfo || !agentBModelInfo) return jsonResponse(request, env, { error: "Unsupported model selection" }, 400); const headers = corsHeaders(request, env, "text/event-stream; charset=utf-8"); if (!headers) return jsonResponse(request, env, { error: "Origin not allowed" }, 403); headers["Cache-Control"] = "no-cache"; const { readable, writable } = new TransformStream(); const writer = writable.getWriter(); const encoder = new TextEncoder(); (async () => { const transcript = []; try { for (let round = 1; round <= rounds; round += 1) { await streamAgentResponse({ env, modelInfo: agentAModelInfo, systemPrompt: agentASystemPrompt, topic, transcript, agent: "A", round, writer, encoder, temperature, reasoningMode }); await streamAgentResponse({ env, modelInfo: agentBModelInfo, systemPrompt: agentBSystemPrompt, topic, transcript, agent: "B", round, writer, encoder, temperature, reasoningMode }); } await writeEvent(writer, encoder, "done", { message: "Conversation completed" }); } catch (_) { await writeEvent(writer, encoder, "error", { message: AI_ERROR_MESSAGE }); } finally { await writer.close(); } })(); return new Response(readable, { headers }); }
export default { async fetch(request, env) { const url = new URL(request.url); if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: corsHeaders(request, env, null) || { "Vary": "Origin" } }); if (url.pathname === "/health") return request.method === "GET" ? jsonResponse(request, env, { ok: true }) : jsonResponse(request, env, { error: "Method not allowed" }, 405); if (url.pathname === "/models") return request.method === "GET" ? jsonResponse(request, env, { models: SUPPORTED_MODELS, defaults: { agentA: DEFAULT_AGENT_A_MODEL, agentB: DEFAULT_AGENT_B_MODEL }, prompts: { agentA: DEFAULT_AGENT_A_SYSTEM_PROMPT, agentB: DEFAULT_AGENT_B_SYSTEM_PROMPT }, settings: { defaultRounds: DEFAULT_ROUNDS, defaultTemperature: 0.7, reasoningModes: REASONING_MODES } }) : jsonResponse(request, env, { error: "Method not allowed" }, 405); if (url.pathname === "/debate") return request.method === "POST" ? handleDebate(request, env) : jsonResponse(request, env, { error: "Method not allowed" }, 405); return jsonResponse(request, env, { error: "Not found" }, 404); } };
export { SUPPORTED_MODELS, readWorkersAIStream, handleDebate };
